name: Package Meter Readings Lambda Function

on:
  push:
    paths:
      - 'meter-readings/**'
  workflow_dispatch:

jobs:
  package-lambda:
    name: Build Lambda Deployment Package
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: meter-readings

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t build
          cp lambda_function.py build/

      - name: Create ZIP package
        run: |
          cd build
          zip -r ../function.zip .

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-function
          path: meter-readings/function.zip
